name: Pipeline Diario Lima-Chiclayo

on:
  schedule:
    # Se ejecuta a la 1:00 AM UTC (que son las 8:00 PM en Lima, Peru)
    - cron: '0 1 * * *'
  workflow_dispatch: # Te permite ejecutarlo manualmente con un boton

jobs:
  extraccion-datos:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar librerias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Scripts de Extraccion (Ingesta -> raw / staging directo)
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        APIFY_API_TOKEN: ${{ secrets.APIFY_API_TOKEN }}
      run: |
        python src/ingest_trends.py
        python src/ingest_traffic.py
        python src/test_apify.py
        python src/ingest_weather.py
        python src/ingest_economy.py

    - name: Ejecutar Transformaciones (Raw -> Staging)
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python src/transform_weather.py
        python src/transform_staging.py

    - name: Actualizar Features de Calendario (Logica Difusa)
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python src/feature_calendar.py
